name: Terraform CICD

on:
  push:
    branches:
      - main
      - develop
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Check
        run: terraform fmt -check
